### ISSUE TITLE
How does one get started

### ISSUE THREAD

**Issue by IceWaffles** [XyeetD/Undetectable-Minecraft-autoclicker-speedbridge#1]
How can one get started with this auto clicker? No download links that I see...

**Comment by one-third-reason** [comment]
Currently to use it you gotta have python installed, and the pynput module installed
After that, download the python file and it should be runnable

I think I should make it an executable file hmm

**Comment by IceWaffles** [comment]
I would say to make it better, you should perhaps make it a fabric mod or something for ease of use? Maybe also a very simple in-game GUI to determine the CPS speed.

**Comment by one-third-reason** [comment]
Sorry but I don't know how to make a minecraft mod, this is more like an external program thing

Anyways about making it to an executable file, I think I wont do it so people can change some stuff in the code if they want to
If it's an executable file already then people cant change stuff in the code, unless it has an input system or something but nahhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh im lazy

**Comment by one-third-reason** [comment]
Anyways I kinda forgot to put a tutorial how to download/run it lol

It'll be a bit hard to use it, and tbh it isn't that great so don't put your hopes too high
